[package]
name = "app"
version = "0.1.0"
authors = ["Dmytro Lysai <d@emphased.net>"]
edition = "2018"

[dependencies]
clap = "2.33"
humansize = "1.1"
humantime = "1.2"
memmap = "0.7"
tagen = { path = "../lib" }